const NODE_INTERPRETER = process.env.WA_NODE_BINARY || '/Users/depp/.nvm/versions/node/v20.20.2/bin/node';

module.exports = {
  apps: [
    {
      name: 'wa-crawler-beau',
      cwd: '/Users/depp/wa-bot/wa-crm-v2',
      script: 'server/waCrawler.cjs',
      interpreter: NODE_INTERPRETER,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      min_uptime: '20s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/tmp/wa-crawler-beau.log',
      error_file: '/tmp/wa-crawler-beau.err.log',
      time: true,
      merge_logs: true,
      env: {
        WA_SESSION_ID: 'beau',
        WA_OWNER: 'Beau',
        WA_API_BASE: 'http://127.0.0.1:3000',
      },
    },
    {
      name: 'wa-crawler-yiyun',
      cwd: '/Users/depp/wa-bot/wa-crm-v2',
      script: 'server/waCrawler.cjs',
      interpreter: NODE_INTERPRETER,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      min_uptime: '20s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/tmp/wa-crawler-yiyun.log',
      error_file: '/tmp/wa-crawler-yiyun.err.log',
      time: true,
      merge_logs: true,
      env: {
        WA_SESSION_ID: 'yiyun',
        WA_OWNER: 'Yiyun',
        WA_API_BASE: 'http://127.0.0.1:3000',
      },
    },
    {
      name: 'wa-crawler-youke',
      cwd: '/Users/depp/wa-bot/wa-crm-v2',
      script: 'server/waCrawler.cjs',
      interpreter: NODE_INTERPRETER,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      min_uptime: '20s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/tmp/wa-crawler-youke.log',
      error_file: '/tmp/wa-crawler-youke.err.log',
      time: true,
      merge_logs: true,
      env: {
        WA_SESSION_ID: 'youke',
        WA_OWNER: 'WangYouKe',
        WA_API_BASE: 'http://127.0.0.1:3000',
      },
    },
    {
      name: 'wa-crawler-jiawen',
      cwd: '/Users/depp/wa-bot/wa-crm-v2',
      script: 'server/waCrawler.cjs',
      interpreter: NODE_INTERPRETER,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      min_uptime: '20s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      out_file: '/tmp/wa-crawler-jiawen.log',
      error_file: '/tmp/wa-crawler-jiawen.err.log',
      time: true,
      merge_logs: true,
      env: {
        WA_SESSION_ID: 'jiawen',
        WA_OWNER: 'Jiawen',
        WA_API_BASE: 'http://127.0.0.1:3000',
      },
    },
  ],
};
